DefaultContentLanguage = "en"
baseURL = "https://www.arjungandhi.com"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en"
summarylength = 10
title = "Arjun Gandhi"

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = ""

# Syntax highlighting
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[params]
author = "Arjun Gandhi"
title = "Arjun Gandhi"
#copyright = "2020-2021"
description = "I make things"
favicon = "favicons/"
keywords = ""
profilePicture = "images/profile.jpg"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = []
doNotLoadAnimations = false
images = ["images/site-feature-image.png"]
mainSections = [""]
# Form Spree Contact Form
# Google Site Verify
# googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# Google Analytics
gtagId="G-7P7MXHJRDG"
# indexDateFormat = "Mon, Jan 2, 2006"
listDateFormat = "Jan, 2006"
# singleDateFormat = "Mon, Jan 2, 2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
disableThemeSwitcher = true
displayMode = "nord-dark"
# google-photos-yoinker
yoinkerVersion = "1.1.5"


[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = true # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex" # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/arjungandhi06/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/arjungandhi"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:contact@arjungandhi.com"

## Menu items

[menu]

[[menu.main]]
identifier = "whoami"
name = "Who am I?"
url = "/"
weight = 100

[[menu.main]]
identifier = "reviews"
name = "What Do People Think?"
url = "/reviews/"
weight = 200

[[menu.main]]
identifier = "projects"
name = "Stuff I've Done"
url = "/projects/"
weight = 300

[[menu.main]]
identifier = "blog"
name = "Latest Projects"
url = "/blog/"
weight = 400

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 500

#Allow Unsafe building
[markup.goldmark.renderer]
unsafe= true

# Deployment
[deployment]

[[deployment.targets]]
URL = "s3://www.arjungandhi.com?region=us-east-1"
name = "arjungandhi.com"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
cloudFrontDistributionID = "E3MKDRE6IOMR91"

[[deployment.matchers]]
# Cache static assets for 20 years.
cacheControl = "max-age=630720000, no-transform, public"
gzip = true
pattern = "^.+\\.(js|css|png|jpg|gif|svg|ttf)$"

[[deployment.matchers]]
gzip = true
pattern = "^.+\\.(html|xml|json)$"
